name: Run Linting

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linting:
    name: Linting
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        tool: ['flake8', 'bandit', 'gitlint']
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pre-commit
          pre-commit install
      - name: Run ${{ matrix.tool }} using pre-commit
        if: ${{ matrix.tool != 'gitlint' }}
        run: |
            pre-commit run ${{ matrix.tool }} --all-files     
      - name: Upload Bandit report
        if: ${{ matrix.tool == 'bandit' }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Bandit-security-report
          path: bandit-report.json
          retention-days: 5
      - name: Run gitlint
        env:
          TITLE: ${{ github.event.pull_request.title }}
        if: ${{ github.event_name == 'pull_request' && matrix.tool == 'gitlint' }}
        run: |
          python -m pip install --upgrade gitlint
          echo "$TITLE" | gitlint